### ISSUE TITLE
Cannot select which fragment to insert

### ISSUE THREAD

**Issue by jdhalbert** [massCodeIO/assistant-vscode#6]
When inserting a snippet into VS Code, only the first fragment is inserted. It is not possible to see or insert any other fragment.

**Comment by antonreshetov** [comment]
It's not a bug. The functionality provides work only with the first snippet fragment.

**Comment by jdhalbert** [comment]
Sorry, I should have labeled it as a feature request. I implemented it and submitted a pull request.

**Comment by antonreshetov** [comment]
Closed because it was added in #7
